---
- hosts: servers
  become: true
  tasks:
    - name: Actualizar cache de software de apt
      apt:
        update_cache: yes

    - name: Instalar Apache
      apt:
        name: apache2
        state: present

    - name: Instalar Cowsay
      apt:
        name: cowsay
        state: present

    - name: Crear un archivo
      copy:
        content: "Este es un archivo de prueba\n"
        dest: /home/vagrant/archivo_prueba.txt

    - name: Copiar archivos
      copy:
        src: /home/vagrant/archivo_prueba.txt
        dest: /home/vagrant/archivo_copia.txt

    - name: Crear carpetas
      file:
        path: /home/vagrant/carpeta_prueba
        state: directory

    - name: Iniciar el servicio Apache
      service:
        name: apache2
        state: started

    - name: Agregar un usuario al servidor
      user:
        name: nuevo_usuario
        state: present
        shell: /bin/bash

    - name: Ejecutar un script en el servidor
      shell: |
        echo "echo 'Este es un script ejecutado por Ansible'" > /home/vagrant/ejecutar.sh
        bash /home/vagrant/ejecutar.sh
